// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkXQTnw8p_e95eOrPhcJAC5Q3hLsKDUbM',
    appId: '1:964337865434:web:0a8134909ccd48ddb58be3',
    messagingSenderId: '964337865434',
    projectId: 'cuetor-761aa',
    authDomain: 'cuetor-761aa.firebaseapp.com',
    databaseURL:
        'https://cuetor-761aa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cuetor-761aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZFu2cjE3egfjxhj8wlteEkAOCwtFxbng',
    appId: '1:964337865434:android:ce90ffcebfa5d0e1b58be3',
    messagingSenderId: '964337865434',
    projectId: 'cuetor-761aa',
    databaseURL:
        'https://cuetor-761aa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cuetor-761aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-jX0zK9lZuFufSz_fHd_c3OUOfollyvc',
    appId: '1:964337865434:ios:30f977c70f9ffd4ab58be3',
    messagingSenderId: '964337865434',
    projectId: 'cuetor-761aa',
    databaseURL:
        'https://cuetor-761aa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cuetor-761aa.appspot.com',
    iosClientId:
        '964337865434-ft5ahf3u4dh7pp21ku5ah1olscau20gm.apps.googleusercontent.com',
    iosBundleId: 'com.cuetorucl.cuetor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-jX0zK9lZuFufSz_fHd_c3OUOfollyvc',
    appId: '1:964337865434:ios:30f977c70f9ffd4ab58be3',
    messagingSenderId: '964337865434',
    projectId: 'cuetor-761aa',
    databaseURL:
        'https://cuetor-761aa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cuetor-761aa.appspot.com',
    iosClientId:
        '964337865434-ft5ahf3u4dh7pp21ku5ah1olscau20gm.apps.googleusercontent.com',
    iosBundleId: 'com.cuetorucl.cuetor',
  );
}
